name: Publish to npmjs on release
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write       # required for npm OIDC

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Compare the tag and version
        run: |
          NODE_VERSION=$(node -p -e "require('./package.json').version")
          LATEST_TAG=$(git describe --tags --abbrev=0)
          if [ "v$NODE_VERSION" != $LATEST_TAG ]; then echo "Github tag ($LATEST_TAG) and version ($NODE_VERSION) don't match" && exit 1; fi

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24       #  Actions will be forced to run with Node.js 24 by default starting June 16th
          registry-url: "https://registry.npmjs.org"

      - name: Upgrade npm
        run: npm install -g npm@latest    # ensure npm >= 11.5.1

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish --access=public
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true